In [1]:
load_session("W3525-7lines.sobj")

In [2]:
len(res)

100

In [12]:
res[1][0]

[ 2  2  2  2  2  2  1]
[ 2  2  2 -2 -2 -1 -2]
[ 3 -2 -2  0  0  2 -2]
[ 2 -3  2  0  0 -2  2]
[ 2  2 -3  0  0 -2  2]
[ 0  0  0  4 -1 -2 -2]
[ 0  0  0  1 -4  2  2]

In [3]:
def getMatType(Mat):
    vals3=[]
    for i in range(Mat.nrows()-2):
        for j in range(i+1,Mat.nrows()):
            for k in range(j+1,Mat.nrows()):
                rSum = 0
                for l in range(Mat.ncols()):
                    rSum = rSum + abs(Mat[i][l]*Mat[j][l]*Mat[k][l])
                vals3.append(abs(rSum))
    vals2=[]
    for i in range(Mat.nrows()-1):
        for j in range(i+1,Mat.nrows()):
            rSum = 0
            for l in range(Mat.ncols()):
                rSum = rSum + abs(Mat[i][l]*Mat[j][l])
            vals2.append(rSum)
    return(sorted(vals2),sorted(vals3))
            
            


MaxV=5
codeBase = MaxV+1
nR=6
cB=vector([codeBase^(nR-j) for j in range(nR+1)])
print(cB)
print()
resLen=len(res)
absres=[matrix(7,7,[sorted([abs(res[j][0][l][k]) for k in range(7)]) for l in range(7)]).transpose() for j in range(100)]
ares=[matrix(7,7,[[abs(res[j][0][l][k]) for k in range(7)] for l in range(7)]) for j in range(resLen)]
#print(cB*ares[0]),sorted(cB*ares[0].transpose()))
print(res[0][0])
print(ares[0])  
typeS=[]
Mats=[]
print(resLen)
for Min in range(resLen):
    #nType = sorted(cB*ares[Min])#sorted(cB*ares[Min].transpose())
    #nType2 = nType # sorted(cB*ares[Min].transpose()),sorted(cB*ares[Min])
    nType=getMatType(res[Min][0].transpose())
    nType2=getMatType(res[Min][0])
    if (not(nType in typeS) and not(nType2 in typeS)):
        typeS.append(nType)
        Mats.append(res[Min][0])
print(len(typeS))
for i in range(len(Mats)):
    print("------------")
    print(Mats[i])

(46656, 7776, 1296, 216, 36, 6, 1)

[ 2  2  2  2  2  2  1]
[ 2  2  2 -2 -2 -1 -2]
[ 2 -2 -1  2 -2  2 -2]
[ 1  2 -2  2 -2 -2  2]
[ 2 -3  2  0  0 -2  2]
[ 2  0 -2 -3  0  2  2]
[ 2  0 -2  0  3 -2 -2]
[2 2 2 2 2 2 1]
[2 2 2 2 2 1 2]
[2 2 1 2 2 2 2]
[1 2 2 2 2 2 2]
[2 3 2 0 0 2 2]
[2 0 2 3 0 2 2]
[2 0 2 0 3 2 2]
100
38
------------
[ 2  2  2  2  2  2  1]
[ 2  2  2 -2 -2 -1 -2]
[ 2 -2 -1  2 -2  2 -2]
[ 1  2 -2  2 -2 -2  2]
[ 2 -3  2  0  0 -2  2]
[ 2  0 -2 -3  0  2  2]
[ 2  0 -2  0  3 -2 -2]
------------
[ 2  2  2  2  2  2  1]
[ 2  2  2 -2 -2 -1 -2]
[ 3 -2 -2  0  0  2 -2]
[ 2 -3  2  0  0 -2  2]
[ 2  2 -3  0  0 -2  2]
[ 0  0  0  4 -1 -2 -2]
[ 0  0  0  1 -4  2  2]
------------
[ 2  2  2  2  2  2  1]
[ 3  2 -2 -2  0  0 -2]
[ 2 -3 -2  0  2  0  2]
[ 2 -2  3  0  0 -2 -2]
[ 2  0  0  1 -4  0  2]
[ 0  2  0  0  1 -4  2]
[ 0  0  2 -4  0  1  2]
------------
[ 2  2  2  2  2  2  1]
[ 3 -3  1  1 -1  0 -2]
[ 3  1 -3  0 -1 -1  2]
[ 1  1 -1 -3  0  3 -2]
[ 1  1  0 -1  3 -3 -2]
[ 1  0  3 -3 -1 -1  2]
[ 0  3  1  

In [117]:
ares=matrix(2,2,[[0,0],[1,1]])
print(ares.nrows())
print(ares)
print (i : i in range(1,2))

SyntaxError: invalid syntax (<ipython-input-117-b1d864b1fa20>, line 4)

In [114]:
list(matrix(2,2,[1,2,3,4])),list([4,5])

([(1, 2), (3, 4)], [4, 5])

In [115]:
absMat=matrix

NameError: name 'absMat' is not defined

In [7]:
mat=res[0][0]
g=Graph(mat)
print(mat)

ValueError: there must be one or two nonzero entries per column in an incidence matrix, got entries [2, 2, 2, 1, 2, 2, 2] in column 0

In [ ]:
mat=res[0][0]
import numpy as np
mat1=np.array(mat)
g=(mat1!=0)*1
gs=matrix(g)
#Graph(gs)
h=ones_matrix(7)
Graph(h)



In [7]:
type(gs)

<class 'sage.matrix.matrix_integer_dense.Matrix_integer_dense'>